<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62109" started-at="2020-09-13T01:23:55Z" finished-at="2020-09-13T01:24:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62109" started-at="2020-09-13T01:23:55Z" finished-at="2020-09-13T01:24:57Z">
      <class name="Xpath.Topic_04_WebBrowser">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="BeforeTest" is-config="true" duration-ms="6859" started-at="2020-09-13T08:23:55Z" finished-at="2020-09-13T08:24:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="TC_01_Url()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="TC_01_Url" duration-ms="22496" started-at="2020-09-13T08:24:02Z" finished-at="2020-09-13T08:24:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_Url -->
        <test-method status="PASS" signature="TC_02_Title()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="TC_02_Title" duration-ms="15096" started-at="2020-09-13T08:24:24Z" finished-at="2020-09-13T08:24:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_Title -->
        <test-method status="PASS" signature="TC_03_Navigate()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="TC_03_Navigate" duration-ms="14657" started-at="2020-09-13T08:24:39Z" finished-at="2020-09-13T08:24:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_Navigate -->
        <test-method status="FAIL" signature="TC_04_Page_Source()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="TC_04_Page_Source" duration-ms="2368" started-at="2020-09-13T08:24:54Z" finished-at="2020-09-13T08:24:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Xpath.Topic_04_WebBrowser.TC_04_Page_Source(Topic_04_WebBrowser.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_Page_Source -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:Xpath.Topic_04_WebBrowser@573f2bb1]" name="AfterTest" is-config="true" duration-ms="604" started-at="2020-09-13T08:24:56Z" finished-at="2020-09-13T08:24:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- Xpath.Topic_04_WebBrowser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
